services:
  backend:
    build:
      context: ./backend
    image: sistventa-maced-backend:local
    container_name: sistventa-maced-backend
    ports:
      - "2080:8080"
    env_file:
      - .env
    environment:
      PORT: 8080
      APP_TIMEZONE: America/Lima
      TZ: America/Lima
